### ISSUE TITLE
Error on running CANalyzat0r in docker

### ISSUE THREAD

**Issue by JeremyLebon** [schutzwerk/CANalyzat0r#11]
I want to run the docker container of my Windows PC.

The docker build works fine. 

But when running the docker container I get the following error
![image](https://user-images.githubusercontent.com/11572615/85405790-32fb3300-b561-11ea-9a3d-bc4ddca7fe19.png)

It looks to me that I can't make a connection to a server. Is this the Sqlite server? I don't know.

Thanks for the feedback

**Comment by ps1337** [comment]
I guess this won't work for various reasons, two of them being:

1. You need an X server instance on your windows machine. The container needs it to open the GUI.

2. This tool requires SocketCAN which doesn't work with windows. 




-----Original Message-----

**Comment by JeremyLebon** [comment]
Ok, thanks. I was just a quick try on windows. I will try it on Ubuntu
