### ISSUE TITLE
Migrate application to Pyside2

### ISSUE THREAD

**Issue by totocaca123** [schutzwerk/CANalyzat0r#12]
Migration to Pyside2 as it contains more features

**Comment by ps1337** [comment]
Good idea, I might give that a try at some point. Not sure how many breaking changes there are though.

(PRs welcome) 

-----Original Message-----

**Comment by totocaca123** [comment]
I started to work on it - still some issue but change is not huge

**Comment by ps1337** [comment]
Thanks! 

-----Original Message-----
