### ISSUE TITLE
Raspberry

### ISSUE THREAD

**Issue by EdsonRod** [schutzwerk/CANalyzat0r#13]
Would it be possible to run on the Raspberry PI?

**Comment by ps1337** [comment]
We haven't tested it but I think the easiest way would be to build the docker image on the raspi using the Ubuntu arm base image. In theory this should work without any problems :D please report back after you've tried it :) 

-----Original Message-----

**Comment by EdsonRod** [comment]
I don't  expert in Linux. Do you can help me?
Thanks.

**Comment by ps1337** [comment]
- clone the repo
- cd into the docker folder
- sudo make build
- sudo make run

-----Original Message-----
