### ISSUE TITLE
Can't install on Kali 2020.4

### ISSUE THREAD

**Issue by ghost** [schutzwerk/CANalyzat0r#14]
Hi,

I can't install canalyzat0r on Kali 2020.4, since PySide is depending only on Python3.5 and older.

I've tried reproducing the installation using PyEnv, but the issue persist.

Do you have an AppImage of CANalyzat0r, or you can update all dependencies to Python3.8 and later.

Regards,

**Comment by ps1337** [comment]
Yo, I think the quickest solution would be to use docker since I'd don't know whether we can update all dependencies without issues. 

-----Original Message-----

**Comment by ghost** [comment]
The Docker solution is good but not enough, and native.

You can either update dependencies with issues, as it will take sometime to do, or package everything in one single file as an AppImage.
I personally prefer AppImages, as it doesn't require a single dependency, everything is contained and sandboxed in a single file.

**Comment by ps1337** [comment]
Imo docker containers should be fitting for everyone since you can customize them however you want and they are natively supported by Linux. 

But if you're willing to create an app image you can open a PR and we can add it to this repo of course. 

-----Original Message-----

**Comment by ghost** [comment]
No problem
I'll try to create one, open PR and notify you once done.

I just hope you'll update it with all its dependencies one day, it's really a useful and handy tool ;)

**Comment by ps1337** [comment]
Yep, thanks for the issue. I'll look into it once I have time to do so :)
