### ISSUE TITLE
How to read ECU EEPROM via OBD/CAN?

### ISSUE THREAD

**Issue by brandonros** [schutzwerk/CANalyzat0r#6]
I apologize in advance that this question isn't specific to this project.

How are tuning manufacturers able to download the EEPROM from the ECU via OBD-II, tune it, then reupload it? For example, do Bosch ECUs have a special proprietary command that is not documented anywhere to send the ECU into a boot mode?

Any information you can share would be helpful.

**Comment by sw-pschmied** [comment]
Hello there.

CANalyzat0r may be able to do this if you have knowledge of the correct CAN messages to send, however it's not built to support this out of the box.

But as always with automotive systems:

![spongebob](https://memegenerator.net/img/instances/34334167/anything-is-possible.jpg)
