### ISSUE TITLE
working usb-can adapters

### ISSUE THREAD

**Issue by NeoFromMatrix** [schutzwerk/CANalyzat0r#8]
I know this is pretty hardware agnostic but for getting started it might be interesting to provide a list of known working usb-can adapters. 

Did anyone try the Ross-Tech HEX-V2?

**Comment by sw-pschmied** [comment]
Hello :)

We'll add a note regarding this in the future. Until then: All SocketCAN adapters (like USB2CAN) are supported.

Thanks!

**Comment by sw-pschmied** [comment]
Added a short note to `README.md`, please report  back in case more adapters have been successfully tested.
